### ISSUE TITLE
pkgdown error

### ISSUE THREAD

**Issue by maelle** [ropensci/BaseSet#66]
Via https://ropensci.r-universe.dev/builds

```r
! All topics must be included in reference index
✖ Missing topics: dimnames.TidySet, names.TidySet
ℹ Either add to _pkgdown.yml or use @keywords internal
```

You can use `pkgdown::check_pkgdown()` to check the config file without building the site.

**Comment by llrs** [comment]
Thanks, I didn't notice yesterday. I always forget to check before pushing to check this as in most packages I don't have to manually set them. I was just working on a git hook using `check_pkgdown` before pushing to prevent those kind of errors. Will fix soon

**Comment by maelle** [comment]
Interesting idea to use a git hook! (I had seen GHA workflows)

**Comment by llrs** [comment]
Yes, pretty minimal and easy https://github.com/llrs/rutils/blob/master/inst/pre-push in repo/.git/hooks (with execution permission).
I'm working to automate some steps/config I usually do (or rare things that are hard to setup).

**Comment by maelle** [comment]
do you use the precommit R package or "just" Git?

**Comment by llrs** [comment]
Just git. There is an issue with the python [pre-commit](https://pre-commit.com/) dependency of the package inside Rstudio https://github.com/rstudio/rstudio/issues/6471 that lead me to this.

**Comment by llrs** [comment]
The webpage should be fixed now (but I have in place a failing test to remind me where to continue working). 

It seems that the hooks must be in place before the Rstudio opens (restarting the project doesn't work), and I end up doing it from the terminal.

**Comment by maelle** [comment]
Thank you!!
