### ISSUE TITLE
conda-forge recipe

### ISSUE THREAD

**Issue by mjsteinbaugh** [ropensci/BaseSet#67]
Hi @llrs ,

Great work on the BaseSet package. I'm using this to import GAF files from the Gene Ontology website. I'm working on creating a conda-forge recipe for the CRAN package, and wanted to double check that the dependencies look good.

Pull request is here: https://github.com/conda-forge/staged-recipes/pull/24781

In particular, anything missing from the `meta.yaml`?
https://github.com/conda-forge/staged-recipes/pull/24781/files#diff-4ce869af10a28f3d0dd76d98c4eab3e54bd07c8f1ab72793f828ce87772515c0

Best,
Mike

**Comment by llrs** [comment]
Hi Mike! Happy to hear from users and see you want it in other places too. I was puzzled how this packages had so many downloads :D 

I am not familiar with how conda-forge recipes  are used. As long as r-base has also the  methods and utils packages it should be fine. 
I see there is some mention to BiocManager (in the source url), it shouldn't be needed unless you want to have some of the suggested packages. 
I might remove some dependencies before 1.0.0: magrittr and dplyr. Would it make it easier to built it?

**Comment by mjsteinbaugh** [comment]
Ah the BiocManager reference is a typo in the recipe. Missed that thanks!

**Comment by mjsteinbaugh** [comment]
magrittr and dplyr are used in a lot of other conda-forge recipes, all good

**Comment by mjsteinbaugh** [comment]
This will be up on conda-forge soon!
